trigger:
  branches:
    include:
    - master
    - develop
  paths:
    exclude:
    - 'README.md'
    - '**/*.md'

pr:
  branches:
    include:
    - master
    - develop
  paths:
    exclude:
    - 'README.md'
    - '**/*.md'

pool:
  name: Azure Pipelines
  demands: msbuild
  vmImage: windows-latest

#here is where we set the version number (Build.BuildNumber)
name: 2.1.0

steps:
- task: NuGetToolInstaller@1
  displayName: 'Use NuGet '

- task: NuGetCommand@2
  displayName: 'NuGet restore'
  inputs:
    restoreSolution: src/Xablu.WebApiClient/Xablu.WebApiClient.csproj

- task: MSBuild@1
  displayName: 'Build project Xablu.WebApiClient.csproj'
  inputs:
    solution: src/Xablu.WebApiClient/Xablu.WebApiClient.csproj
    configuration: 'Release'
    msbuildArguments: '/t:restore;build;pack /p:PackageVersion=$(Build.BuildNumber) /p:PackageOutputPath=$(build.artifactstagingdirectory)/public  /p:AssemblyFileVersion=$(Build.BuildNumber) '
- task: CopyFiles@2
  displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
  inputs:
    SourceFolder: '$(build.sourcesdirectory)'
    Contents: '**\bin\Release\**\*.nupkg'
    TargetFolder: '$(build.artifactstagingdirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'